apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-n3-net
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/mlx_vf_n3_dpdk
spec:
  config: '{
  "type": "sriov",
  "cniVersion": "0.3.1",
  "name": "sriov-n3-net",
  "ipam": {
    "type": "host-local",
    "subnet": "10.56.217.0/24",
    "routes": [{
      "dst": "0.0.0.0/0"
    }],
    "gateway": "10.56.217.1"
  }
}'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-n6-net
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/mlx_vf_n6_dpdk
spec:
  config: '{
    "type": "sriov",
    "cniVersion": "0.3.1",
    "name": "sriov-n6-net",
    "ipam": {
      "type": "host-local",
      "subnet": "10.56.218.0/24",
      "gateway": "10.56.218.1"
    }
  }'
